docs/user-guide/getting-started.md

This should work fine for other distros of Linux. Apparently on WSL2 `uname -o` returns: `GNU/Linux`

Support WSL2 in the wget cmd.

---

README.md

In order to use the results of KubeHound programmatically, we can showcase a few example in common language like python.

Add data query pattern from python

---

pkg/config/builder.go
pkg/config/config.go
pkg/kubehound/graph/builder.go

This PR propose a fix for #144 by adding a config to allow continuing building the graph even after there are some errors.
The default config is to continue on error, but print error message.
The long term solution will be to add an error handling module that tracks and display the error, criticality and source of the issues in a human readable way.
The error message should be very explicit that it may create an incomplete graph and thus cause inaccurate (false negative) results.

[ASENG-868] Implement StopOnError config for graph building

---

README.md

- add a `cd` command between `git clone...` and `make...`
- Added an article to the beginning of a sentence - hoping this is a match, stylistically.

Suggestion to add a cd between 'git clone' and 'make'

---

README.md

Add a simple link to the example queries so it's easier to find.
This should fix or at least help a bit with https://github.com/DataDog/KubeHound/issues/152

[DOC] Add link to example queries doc

---

pkg/collector/k8s_api_test.go

Small refacfor for unit tests in k8s API collector

Refactor unit tests

---

cmd/kubehound-ingestor/main.go
cmd/kubehound/main.go
pkg/collector/collector.go
pkg/collector/file.go
pkg/collector/k8s_api.go
pkg/kubehound/ingestor/pipeline/ingest_resources.go
pkg/kubehound/storage/cache/memcache_provider.go
pkg/kubehound/storage/cache/memcache_writer.go
pkg/kubehound/storage/graphdb/janusgraph_provider.go
pkg/kubehound/storage/storedb/mongo_provider.go
pkg/telemetry/profiler/profiler.go
pkg/telemetry/statsd/statsd.go
pkg/telemetry/tag/tags.go
pkg/telemetry/tracer/tracer.go

During the system stumbled on a race condition in the tags. This bug is triggered when the slice for the tags grows enough that it requires a new allocation.
This fix should prevent most of the race condition. 
Ref: https://medium.com/@cep21/gos-append-is-not-always-thread-safe-a3034db7975

Fix-tag-race-condition

---

pkg/collector/file.go
pkg/collector/k8s_api.go
pkg/dump/writer/file_writer.go
pkg/dump/writer/tar_writer.go
pkg/kubehound/core/core_live.go
pkg/kubehound/graph/builder.go
pkg/kubehound/storage/graphdb/janusgraph_edge_writer.go
pkg/kubehound/storage/graphdb/janusgraph_vertex_writer.go
pkg/kubehound/storage/storedb/mongo_writer.go

Change the status of the span when failing

Fix span - return err status

---

.github/workflows/linter.yml
.github/workflows/release.yml
.github/workflows/system-test.yml
.github/workflows/unit-test.yml
go.mod
go.sum
pkg/dump/writer/file_writer.go
pkg/dump/writer/file_writer_test.go
pkg/dump/writer/fs_writer.go
pkg/dump/writer/fs_writer_test.go
pkg/dump/writer/mockwriter/writer.go
pkg/dump/writer/tar_writer.go
pkg/dump/writer/tar_writer_test.go
pkg/dump/writer/writer.go

Refactor the writer to be compatible with the collector. The collector needs to have an abstract layer k8sTypeList, so it means we can no longer dump raw files directly, we need to consolidate all the entries for each files first.
For the file writer, we build a buffer for each file, then write it to the filesystem [buffer -> raw fs.FS]
For the tar writer, there is one more step, instead of writing directly to the tar, we write the file to a "memory fs" using afero lib. [buffer --> aerofs FS --> tar fs.FS]
This allows to support for both writer, partial multi-threading.

Refactor writers (multi-thread + enveloped k8s type_

---

pkg/collector/file.go

If most of the kubernetes entities, files are not required (for instance every namespaced entities).

[File collector] Skip file when not exist

---

pkg/collector/k8s_api_faker.go
pkg/dump/pipeline/pipeline.go
pkg/dump/pipeline/pipeline_faker.go
pkg/dump/pipeline/pipeline_test.go

Refactor the pipeline ingestor to include more unit tests.

[Dumper] Refactor pipeline ingestor

---

deployments/kubehound/mongo/docker-healthcheck

Fix a secondary issue raised in #143.
Thanks @kovacs-levent for pointing it out and finding the origin of the issue
Use `mongosh` instead of `mongo` in the healthcheck script. As pointed out, `mongo` has been [deprecated](https://www.mongodb.com/docs/manual/release-notes/6.0-compatibility/#legacy-mongo-shell-removed) for version > 6.0

Use `mongosh` instead of `mongo`

---

cmd/kubehound/grpc_client.go
pkg/config/config_test.go
pkg/config/ingestor.go
pkg/kubehound/core/core_grpc_client.go

Support for TLS in Kubehound collector, even if the kubehound ingestor does not currently support it, we can expose the GRPC endpoint after a TLS broker/proxy.
A fix also in the kubehound collector to use inline args.

Support for TLS in kubehound collector

---

.gitignore
datadog/.terraform.lock.hcl
go.mod
static-analysis.datadog.yml
test/setup/util.sh

Fixes:
* Adding terraform files to gitignore
* adding terraform lock file
* Bash cleanup
* go mod tidy

Some cleanup

---

Makefile
cmd/kubehound/grpc_client.go
cmd/kubehound/ingestor.go

Merge kubehound-ingestor into kubehound.
Adding a new subcommand: `ingest` to run the grpc server.

merge binaries into one

---

pkg/ingestor/api/api.go
pkg/ingestor/api/api_test.go

Fixing race condition on `TestIngestorAPI_isAlreadyIngested`.
running no longer trigger errors:
* ` go test -timeout 30s -run ^TestIngestorAPI_isAlreadyIngested$ github.com/DataDog/KubeHound/pkg/ingestor/api -v -race -count 20`

Fix unit test

---

pkg/cmd/dump.go
pkg/cmd/util.go
pkg/collector/k8s_api.go
pkg/config/collector.go
pkg/config/config.go
pkg/globals/tags.go
pkg/telemetry/log/logger.go
test/system/kubehound.yaml
test/system/kubehound_dump.yaml
test/system/setup_test.go

By default when collecting/dumping a cluster configuration, kubehound will ask confirmation.
A new flag has been setup to bypass it:
* `-y` or `--non-interactive`

Interactive mod (safe mod) for collecting cluster

---

test/system/setup_test.go

Create error on conflict for GRPC server in system tests.

small fix for system-tests

---

pkg/cmd/util.go
pkg/ingestor/puller/puller_test.go
test/system/kubehound_dump.yaml

Fix null pointer exception on interactive mod.

Fix interactive mod

---

cmd/kubehound/root.go
pkg/backend/containers.go
pkg/collector/k8s_api.go

This PR add some logs around error handling, fixes some small issues and add some text at the end of ingestion to point to the UI.

Better logs

---

pkg/telemetry/log/logger.go
pkg/telemetry/log/text_formatter.go

In order to make console output more user friendly, lets remove some fields that are unnecessary for human consumption (team, component, service). `run_id` is already printed for "typical use cases" in the logs, so removing it as well.

Add custom filter for text_formatter

---

deployments/kubehound/kubegraph/Dockerfile

Adding grpcurl to allow rehydrating on restart.
It does not do the rehydration, it has to add ` grpcurl -plaintext -format text 127.0.0.1:9000 grpc.API.RehydrateLatest`  in the startup scripts.

adding grpcurl to rehydrate on restart

---

.github/workflows/datadog-static-analysis.yml
static-analysis.datadog.yml

This PR adds a GitHub action to run the Datadog static analysis product.

Run Datadog static analyzer CI best practices lint rules

---

cmd/kubehound/dumper.go
cmd/kubehound/ingest.go
pkg/cmd/dump.go
pkg/config/collector.go
pkg/config/config.go
pkg/config/config_test.go
pkg/kubehound/core/core_dump.go
test/system/setup_test.go

Removing the flags for the input/output for `ingest local` and `dump local`. Now it will get passed through the first argument:
* `kubehound dump local [directory to dump the data]`
* `kubehound ingest local [directory or tar.gz path] --cluster <cluster_name>`
Also now the default behavior is to create a compressed file. So the `--compress` has been changed to `--no-compress`.
Note: another PR will be made for the docs

Use positionnal argument for directory/file input/output path

---

.github/workflows/buildx.yml
Dockerfile

In order to "enable" the one liner installer `wget https://github.com/DataDog/KubeHound/releases/download/latest/kubehound-$(uname -o | sed 's/GNU\///g')-$(uname -m) -O kubehound` we need to modify the `darwin-aarch` to `darwin-arm64`.

Fix-darwin-arm-release

---

cmd/kubehound/backend.go
cmd/kubehound/dumper.go
pkg/collector/k8s_api.go
pkg/dump/pipeline/pipeline.go
pkg/kubehound/core/core_grpc_client.go

Adding flags to start the ingestion after a local dump:
* `--ingest`: to start the ingestion
* `--backend`: to start the backend
Also added some logs based some users feedback to let the user know how the dump/ingest is progressing.

local-ingest-dump-pipeline

---

Dockerfile
docs/dev-guide/getting-started.md

Fix:
* UI typo in the doc
* Fix the upper case to match the `uname -o` output

Jt-dd/fixes-release-docs

---

cmd/kubehound/dev.go
deployments/kubehound/datadog/Dockerfile
deployments/kubehound/docker-compose.dev.datadog.yaml
deployments/kubehound/docker-compose.release.datadog.yaml
pkg/backend/project.go

Fix datadog image. Currently running an error if kubehound start with Datadog image.
```
DD_API_KEY="as" DD_APP_KEY="asd" kubehound
INFO[03:28:20] Loading application configuration from default embedded
INFO[03:28:20] Using /Users/julien.terriac/.config/kubehound.yaml for default config
INFO[03:28:20] Initializing application telemetry
WARN[03:28:20] Telemetry disabled via configuration
INFO[03:28:20] Loading backend from default embedded
INFO[03:28:20] Spawning the kubehound stack
[+] Running 2/2
✔ datadog Pulled                                                                                                                                                                                                                                                             74.8s
✔ 93ad6f59c0e8 Pull …
```

Fix datadog image

---

.github/workflows/datadog-static-analysis.yml
.github/workflows/system-test.yml

Reduce default privileges on the `GITHUB_TOKEN`. Limit the scope to `Read repository contents and packages permissions`.
Adding permission manually to each workflows.

Fix workflows RBAC

---

pkg/backend/project.go

As #251 mention when running KubeHound with `DD_APP_KEY` and `DD_API_KEY`, it crashes since we are mounting volumes from the embed files.
So if the key are being set, we assume the agent is already running anyway. The Datadog agent can still be launched using the `dev` files/cmd.

Fix datadog agent release

---

Dockerfile
Makefile
docker-bake.hcl

The binary in the release page are using the latest flag. 
```
INFO[21:02:00] Loading application configuration from default embedded
INFO[21:02:00] Initializing application telemetry
WARN[21:02:00] Telemetry disabled via configuration
INFO[21:02:00] Loading backend from default embedded
WARN[21:02:00] Loading the kubehound images with tag latest - dev branch detected
INFO[21:02:00] Spawning the kubehound stack
```
This behavior should be kept only for the dev or locally build of KubeHound.
Note: this behavior is not detected in brew release for some reasons ...

Fix-ci-release-branch

---

Makefile

Adding the symbols for debug purposes. This will increase the size by 40mb more or less.

Adding all symbols in KubeHound binary

---

deployments/terraform/.terraform.lock.hcl

From Hashicorp doc, we should commit the `terraform.lock.hcl` file.
Note: 
* https://developer.hashicorp.com/terraform/language/files/dependency-lock

Commiting terraform.lock.hcl

---

.github/workflows/system-test.yml

The `agent-github-action` action is deprecated and the use of the service instead is now recommended:
https://github.com/DataDog/agent-github-action?tab=readme-ov-file#deprecation-notice

[NOJIRA] Using service with official image instead of deprecated github action

---

Dockerfile
Makefile

Removing DWARF symbol on Darwin as it causes the following error:
* Pipeline: darwin/amd64 - https://github.com/DataDog/KubeHound/actions/runs/10827132520/job/30039621994
* Pipeline: darwin/arm64 - https://github.com/DataDog/KubeHound/actions/runs/10827132520/job/30039622608
```
/usr/local/go/pkg/tool/linux_arm64/link: /usr/local/go/pkg/tool/linux_arm64/link: running dsymutil failed: exec: "dsymutil": executable file not found in $PATH
```
So striping the DWARF symbol just for the Darwin Binary.

Fix buildx pipeline for Darwin binary/image

---

deployments/kubehound/docker-compose.release.ingestor.yaml

Fix kubehound image name as it changed to kubehound-binary with `v1.5.0` release

fix kubehound image name

---

.gitignore
configs/etc/kubehound-reference.yaml
deployments/k8s/khaas/values.yaml
docs/architecture.md
docs/dev-guide/getting-started.md
docs/dev-guide/testing.md
docs/dev-guide/wiki.md
docs/reference/attacks/index.md
docs/reference/entities/index.md
docs/references.md
docs/user-guide/advanced-configuration.md
docs/user-guide/common-operations.md
docs/user-guide/getting-started.md
docs/user-guide/khaas-101.md

Updating docs with new features:
* deprecation of `--cluster` flag
* deprecation of `cluster` in config file
* renaming `kubehound-ingestor` image to `kubehound-binary`
Fix:
* typo and syntax

updating docs to v1.5.0 with new features

---

.github/workflows/system-test.yml

Running datadog agent only on branch based PR. As if is not supported yet by Github, the following workaround is possible:
* https://github.com/actions/runner/issues/822

Fix fork based PR system-test

---

configs/etc/kubehound-reference.yaml
configs/etc/kubehound.yaml
deployments/k8s/khaas/conf/ingestor/kubehound.yaml
deployments/k8s/khaas/values.yaml
docs/user-guide/khaas-101.md
pkg/config/collector.go
pkg/config/config.go
pkg/config/config_test.go
pkg/config/ingestor.go
pkg/config/janusgraph.go
pkg/config/mongodb.go
pkg/ingestor/puller/blob/blob.go
pkg/ingestor/puller/blob/blob_test.go
pkg/kubehound/storage/retrier.go
test/system/kubehound_dump.yaml
test/system/setup_test.go

Adding the following env variable for easier setup of the ingestor image:
```yaml
- KH_MONGODB_URL=mongodb://mongodb:27017
- KH_JANUSGRAPH_URL=ws://kubegraph:8182/gremlin
- KH_INGESTOR_API_ENDPOINT=0.0.0.0:9000
- KH_INGESTOR_TEMP_DIR=/tmp/kubehound
- KH_INGESTOR_MAX_ARCHIVE_SIZE=2147483648 # 2GB
- KH_INGESTOR_ARCHIVE_NAME=archive.tar.gz
- KH_INGESTOR_REGION=us-east-1
- KH_INGESTOR_BUCKET_NAME= # s3://<your_bucket>
- AWS_ACCESS_KEY_ID=
- AWS_SECRET_ACCESS_KEY=
- AWS_SESSION_TOKEN= # for aws-vault generated credentials
```
Also fix the issue regarding the `bucket_name` input from the config file/inline args.

add env variable for ingestor/grpc image

---

pkg/config/k8s.go

When deploying the collector inside a k8s cluster, we need to configure one of the two variable:
- `KH_K8S_CLUSTER_NAME_ENV_PTR`: variable indicating env var to use from the k8s cluster/pod to setup the name of the targetted k8s cluster
- `KH_K8S_CLUSTER_NAME`: variable indicating the name of the targetted k8s cluster
Note:
* `KH_K8S_CLUSTER_NAME_ENV_PTR` will overwrite the `KH_K8S_CLUSTER_NAME` env var.

Fix for collector in k8s environment

---

pkg/cmd/dump.go

To match the config file, renaming `--bucket` to `--bucket-url` as an URL is asked as input (i.e. s3://<your_bucket>).

Rename remote bucket flag to bucket-url

---

docs/css/extra.css
docs/dev-guide/getting-started.md
docs/dev-guide/testing.md
docs/khaas/advanced-configuration.md
docs/khaas/deployment.md
docs/khaas/getting-started.md
mkdocs.yml

Creating a dedicated section for KubeHound as a Service. Adding the new env var to setup the cluster name in k8s environment deployment.
Fix:
* Direct URL to code access.
* Renaming remote flag to `bucket-url`.

Update docs v1.5.2

---

cmd/kubehound/dev.go
cmd/kubehound/server.go
deployments/kubehound/docker-compose.dev.ui.yaml
pkg/backend/containers.go

Adding --no-cache for dev command: `kubehound dev --ui --no-cache`. The default behavior now is to use cache when building Docker images.
This avoid spending 10 minutes building the UI...

adding nocache flag for dev commands

---

scripts/dashboard-demo/main.py

Fixing the demo dashboard. We introduced a new attack that "overflow" the attack distribution. I only the keep the top 15 attacks in order to print out the distribution.

Fixing demo dashboard

---

docs/workshop.md
mkdocs.yml

Adding workshop requirements and cheatsheet to allow people to follow easier the workshop.

Adding workshop requirements

---

datadog/span-metrics.tf
pkg/collector/file.go
pkg/collector/k8s_api.go
pkg/ingestor/api/api.go
pkg/ingestor/puller/blob/blob.go
pkg/kubehound/core/core_dump.go
pkg/kubehound/graph/builder.go
pkg/kubehound/providers/providers.go
pkg/kubehound/storage/cache/memcache_provider.go
pkg/kubehound/storage/cache/memcache_writer.go
pkg/kubehound/storage/graphdb/janusgraph_edge_writer.go
pkg/kubehound/storage/graphdb/janusgraph_vertex_writer.go
pkg/kubehound/storage/storedb/mongo_writer.go
pkg/telemetry/events/events.go
pkg/telemetry/log/fields.go
pkg/telemetry/metric/metrics.go
pkg/telemetry/span/spans.go
pkg/telemetry/statsd/statsd.go
pkg/telemetry/tag/tags.go

Reworking the observability stack to get metrics, logs and events from all differentes phases of processing.

Fix observability

---

docs/references.md
pyproject.toml

Adding hacklu presentation for the talk and workshop.

adding hacklu materials

---

docs/dev-guide/getting-started.md

Inform the user that the minimum docker/podman machine must have at least 16GB allocated to prevent bootstrap issues of JVM processes.

doc(requirements): add memory requirements for docker machine.

---

pkg/kubehound/storage/graphdb/janusgraph_provider.go

Fix log typo
`Cleaning cluster%!(EXTRA string=cluster, string=clustername))`

Fix log typo

---

configs/etc/kubehound-reference.yaml
configs/etc/kubehound.yaml
pkg/config/builder.go
pkg/config/config.go
pkg/config/config_test.go
pkg/config/janusgraph.go
pkg/kubehound/storage/graphdb/errors.go
pkg/kubehound/storage/graphdb/janusgraph_edge_writer.go
pkg/kubehound/storage/graphdb/janusgraph_provider.go
pkg/kubehound/storage/graphdb/janusgraph_vertex_writer.go
pkg/kubehound/storage/graphdb/microbatcher.go
pkg/kubehound/storage/graphdb/microbatcher_test.go
pkg/kubehound/storage/graphdb/provider.go
pkg/telemetry/metric/metrics.go

The graphdb entity writers can be subject to unexpected behaviours from the JanusGraph backend (eg. backend not responding due to runtine errors).
The writers have been modified to add resilience to unexpected situation:
- The lock-free microbatcher pattern has been externalised to a dedicated instance to prevent design issues
- The batch processing are bound in time to react to the unresponsive backend issue (default: 60s) 
- A retry pattern allows a batch to be retried with an capped limit. Batchs are lost if the retry max is reached. (default: 3)
- The writer supports parallel insertion workers. (default: 10)
- When a timeout error occurs, each batch size is divided by 2 to reduce the size of each attempt to prevent GraphBinary errors due to too large requests.
Sample warning …

graphdb batch writer resiliency

---

pkg/kubehound/graph/edge/escape_umh_core_pattern.go
pkg/kubehound/storage/storedb/index_builder.go

The `umh_core_pattern` attack is currently linking the attack to all volumes which generates a lot of false positive.
Updating the MongoDB request to link only vulnerable volumes.

Fix umh core pattern attacks

---

cmd/kubehound/config.go
cmd/kubehound/dumper.go
cmd/kubehound/ingest.go
cmd/kubehound/root.go
pkg/config/config.go
pkg/config/config_test.go
pkg/config/ingestor.go

Fixing the following errors (persistentFlag missing):
```
kubehound --config ./configs/etc/kubehound.yaml ingest remote
11:42:57 FATAL unknown flag: --skip-backend app=kubehound
main.main
/Users/asd/go/src/github.com/DataDog/kubehound/cmd/kubehound/main.go:16
runtime.main
/Users/asd/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-arm64/src/runtime/proc.go:272
```
Also fix `kuhehound dump remote` command by triggering ingestion if khaas_server is provided through a config file or command line.

Fix flags for rootcmd

---

pkg/kubehound/storage/graphdb/janusgraph_provider.go

Split the vertices/edges removal queries in smaller batches to prevent large transaction locks.

feat(graphdb): split deletion transactions.

---

.github/workflows/buildx.yml
.github/workflows/datadog-static-analysis.yml
.github/workflows/docker.yml
.github/workflows/docs.yml
.github/workflows/linter.yml
.github/workflows/system-test.yml
.github/workflows/unit-test.yml

* Update GHA step versions and pin them to commit hash.

chore(ci): update step actions.

---

docs/reference/graph/graph.schema.json
docs/reference/graph/graph.yaml

Add MITRE ATT&ck references to the graph schema.
- fix https://github.com/DataDog/KubeHound/issues/151

feat(graph): document mitre attck in schema.

---

pkg/kubehound/graph/adapter/mongo.go
pkg/kubehound/graph/builder.go

If an occurs runs during the edges processing steps, we do not get any error message and the batcher stop (context canceled):
```
18:04:12 ERROR worker: context canceled context canceled app=kubehound dd.span_id=3255329607933268550 dd.trace_id=252869397306062657
18:04:12 INFO Building edge app=kubehound label=ContainerEscapeVarLogSymlink
18:04:12 ERROR worker: context canceled app=kubehound dd.span_id=3255329607933268550 dd.trace_id=252869397306062657
18:04:12 ERROR worker: context canceled app=kubehound dd.span_id=3255329607933268550 dd.trace_id=252869397306062657
18:04:12 ERROR worker: context canceled app=kubehound dd.span_id=3255329607933268550 dd.trace_id=252869397306062657
18:04:12 ERROR run item batcher: context canceled app=kubehound dd.span_id=3255329607933268550 …
```

[Fix] Add resilience and logs when failing during edges insertion step

---

pkg/kubehound/graph/edge/permission_discover.go
pkg/kubehound/models/converter/store.go
test/setup/test-cluster/attacks/IDENTITY_IMPERSONATE.yaml

In some cases, k8s ServiceAccount were added without namespace, which is not possible as they have to be bound to a namespace.
The error comes from the fact that rolebinding can be set on a namespace less service account (will bound automatically bound to the rolebinding one by default).
```
k describe rolebindings rb-test --namespace test                                                        
Name:         rb-test
Labels:       app=test-app
chart_name=test-chart
chart_version=0.1
service=test-svc
team=test-team
Annotations:  helm.sh/hook: post-install,post-upgrade
Role:
Kind:  Role
Name:  rb-test
Subjects:
Kind            Name                Namespace
----            ----                ---------
ServiceAccount  rb-test 
```
So if encountering this usecase, we add the namespace manually …

[Fix] Add rolebinding namespace on namespace less ServiceAccount 

---

Makefile
cmd/kubehound/backend.go
cmd/kubehound/dev.go
cmd/kubehound/dumper.go
cmd/kubehound/root.go
cmd/kubehound/util_default.go
cmd/kubehound/util_no_backend.go
pkg/backend/containers.go
pkg/backend/project.go
pkg/backend/util.go

Docker dependencies are "heavy" and implies CGO complexity.
Adding a specific tag `no_backend` to build a version which is docker free (without specificying this tag, kubehound will be built without docker dependencies).

Kubehound with no Docker lib dependency

---

docs/user-guide/common-operations.md

Document backend overrides capabilities.
- close https://github.com/DataDog/KubeHound/issues/316

chore(doc): document backend overrides capabilities.

---

pkg/ingestor/api/api.go

When launching several time the same ingestion at the same time, it provoques colision in the cache which lead to uncomplete dataset in the graph.
```
*errors.joinError: raw data ingest: ingest: group k8s-pod-group ingest: file collector stream pods: processing K8s pod test-app-84ccb949c-9klm2: cache entry already exists in test and set operation
```
Adding a memory map in the GRPC component to lock runID processing and avoind concurrencies.

[Fix] Concurrency processing of runID

---

pkg/ingestor/api/api.go

Using `sync.Map` instead of mutex + Map for concurrency lock.

Using sync.Map instead of mutex + Map for concurrency lock

---

.github/workflows/buildx.yml

Fixing breaking changes in upload-artifacts v4:
```
Uploading to the same named Artifact multiple times.
Due to how Artifacts are created in this new version, it is no longer possible to upload to the same named Artifact multiple times. You must either split the uploads into multiple Artifacts with different names, or only upload once. Otherwise you will encounter an error.
```
We are getting the following error:
```
Run actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b
With the provided path, there will be 2 files uploaded
Artifact name is valid!
Root directory input is valid!
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```

[Fix] breaking changes in upload-artifacts v4

---

.github/workflows/buildx.yml

Fix artifact name with forbidden character (`/`)

[Fix] Invalid character in build-binary CI job

---

.github/workflows/buildx.yml

Fix missing artifacts in build-binaries CI job
```
Error: Unable to download artifact(s): Artifact not found for name: kubehound
```

[Fix] checkout v4 release missing artifact

---

Makefile
docs/queries/dsl.md

Add documentation notes about Traversal DSL returning paths that need to be mapped to be displayed in Jupyter.
- closes #324

chore(doc): document traversal related dsl returning paths.

---

README.md
docs/dev-guide/getting-started.md
pkg/backend/project.go

Address #326 : building the image from source should not be done straight from main as changes on main are not "pushed" to the registries until a new tag is created, but instead it should be done at a specific tagged commit
- Add checkout instructions in dev-guide
- Add checkout instructions in README
- Add homebrew instructions in README
- In the docker tag selector function, prevent overriding the build tag with "latest" if we are on a detached commit (which is the case when building from a release tag)

(doc) More precise installation instructions

---

docs/user-guide/getting-started.md

A bit of a drive-by but threw me off when getting started

fix(docs): fix typo in getting-started.md

---

deployments/kubehound/ui/README.md

When crafting my own Jupyter Notebook, I was struggling with gremlin interactions with jupyter, and didn't find much examples online, so I added here some tricks/information that were useful.
Add a readme next to the jupyter notebooks with additional information

docs/ui: Add jupyer+gremlin tricks
